POST http://localhost:8888/api/auth0/register
Content-Type: application/json

{
    "mail": "admin@noresply.github.com",
    "username": "admin",
    "password": "123"
}

###

POST http://localhost:8888/api/auth0/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###

POST http://localhost:8888/api/auth0/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6IkV4cHJlc3MtQmx1ZXByaW50IiwiaWF0IjoxNjgxNjI2NTA4LCJleHAiOjE2ODE2MzM3MDh9.LtvuEepfru_4j_6sMYJTDMJXTegXyi5xNY3LpLNxQ14