POST http://localhost:8888/api/auth0/register
Content-Type: application/json

{
    "mail": "admin@noresply.github.com",
    "username": "admin",
    "password": "123"
}

###

POST http://localhost:8888/api/auth0/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###

POST http://localhost:8888/api/auth0/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInN1YklkIjoiYjAzMTFhMDgtNGYwMi00N2FjLTk2YmMtY2Y4Y2NlNWU3MTRiIiwiaXNzIjoiRXhwcmVzcy1CbHVlcHJpbnQiLCJpYXQiOjE2ODIzNjc0MTEsImV4cCI6MTY4MjM3NDYxMX0.dzf0bIhUvD8fkFKFEkRrwRHM9ZibPxdN_rqwKQKLkps